import type { PlaybookBase } from "../types";

export const americanPlaybook: PlaybookBase = {
	title: "The American",
	intro: [
		"You grew up in a big city on the Eastern Seaboard of the United States, the scion of a prominent family, but you detested that life–the formality, the pretension, the venomous hypocrisy–and so you went West. You had adventures, got good with a gun, even joined a traveling show for a time… but then came the curse, and everything changed. You did your best to control it, and some nights were definitely worse than others, but eventually it got to be too much. Even your days were affected by the changes within you; your behavior became reckless and unpredictable. And then you had to run, far away. In the end, it was London calling: a thick, throbbing mass of humanity within which to lose yourself—the whole world and all its lovely pleasures right within your grasp. But the curse has found you, like it always does. Hopefully these new folks, these Hunters you’ve thrown in with, can help you–help you for good, permanent-like—when the time comes.",
	],
	names: {
		nickname: [
			"Wild",
			"Calamity",
			"Buffalo",
			"The Beast",
			"Razor",
			"Smoke",
			"Night Rider",
			"Sureshot",
			"Painkiller",
			"Hard Case",
			"Gravedigger",
			"Dust Devil",
			"Snake Eyes",
			"The Angel",
			"Dynamite",
			"Lone Rider",
			"Whiplash",
			"Knife",
			"Tex",
			"Six-Gun",
			"Doc",
		],
		firstName: [
			"Jake",
			"Jim",
			"Mike",
			"Ross",
			"Roy",
			"Zeke",
			"Travis",
			"Tom",
			"Hank",
			"Frank",
			"Sam",
			"Annie",
			"Elsie",
			"Constance",
			"Laura",
			"Mary",
			"Rose",
			"Sue",
			"Margaret",
			"Sally",
			"Maureen",
		],
		surname: [
			"Anderson",
			"Banton",
			"Ferguson",
			"Fletcher",
			"McBain",
			"Porter",
			"Slade",
			"Larabee",
			"Hu",
			"Kaufmann",
			"O'Neil",
			"Candelora",
			"Navarro",
			"Nelson",
			"Stevens",
			"Carson",
			"Baker",
		],
		realName: [
			"(Chance)",
			"(Morton)",
			"(Newton)",
			"(Maximilian)",
			"(Augustus)",
			"(Julius)",
			"(Gloriana)",
			"(Mildred)",
			"(Beatrice)",
			"(Evangeline)",
			"(Samantha)",
		],
	},
	look: [
		"extravagant coat with fringe on the arms",
		"ten-gallon hat with feathers and rattlesnake tail",
		"bolo tie with turquoise inlay",
		"frayed duster in black",
		"hair in pigtails",
		"shoulder-length hair with beads woven in",
		"mutton chops",
		"pencil mustache",
		"handlebar mustache",
		"cheeks that are always smudged",
		"healthy tan",
		"rangey muscles",
		"sharp cheekbones",
		"split lower lip",
		"calfskin gloves",
		"pocket square of purple silk",
		"jewelry with skull and devil motifs",
		"leather bandolier died saffron yellow",
		"jeweled cigarrillo  case",
		"crocodile boots with lapis detail",
		"ostrich boots with gold embroidery",
		"calfskin boots that have seen better days",
	],
	vices: ["coffin varnish", "Faro", "prostitutes", "opium", "shooting things"],
	questions: [
		"Did you stick out in London society for all the wrong reasons?",
		"Did you use violence to solve a problem?",
		"Did you encourage a fellow Hunter to let loose for a change?",
		"Did you have a raw, passionate sexual encounter during which your feral nature manifested?",
		"Did you share a treasured memory from the States during an intimate moment with another character?",
	],
	abilities: {
		vitality: 1,
		composure: 0,
		reason: 0,
		presence: 1,
		sensitivity: 0,
	},
	masksOfPast: [
		"Narrate a flashback to your childhood that shows the high level of privilege you were born into.",
		"Narrate a flashback to your youth showing what an arrogant, willful brat you were. ",
		"Narrate a flashback to your young adulthood that shows the incident that made you start to resent, even despise, your parents. ",
		"Narrate a flashback to the time after you finally went West that shows you happy and free. ",
		"Narrate a flashback to the incident that caused you to receive the quickening curse. ",
		"Narrate a flashback to the time when the quickening curse caused you to hurt someone you care about.  ",
		"Narrate a flashback showing the incident that caused you to go on the run. ",
	],
	masksOfFuture: 	[
		"<strong>The Guilded Door</strong>: Take the following Condition: Most-Beloved. Tell the other Hunters they can no longer choose The Gilded Door on their own playbook (this does not count as being marked for them). You can never clear Most-Beloved.",
		"<strong>The Moss-Covered Gate</strong>: Narrate a scene in which you receive a letter from one of your parents urging you to return home. What does the letter say? Then tell the Keeper to put The Pinkerton in play. ",
		"<strong>The Darkened Threshold</strong>: Narrate a scene in which you hurt an innocent because of your curse. ",
		"<strong>The Cosmic Passage</strong>: Increase your Sensitivity by 1 (max 3) and reduce your Reason by 2.",
		"<strong>The Blood-Soaked Portal</strong>: Narrate a scene in which you are physically destroyed. This character is now retired. ",
	],
	startingMoves: ["The Quickening"],
	moves: [
		{
			title: "The Quickening",
			text: [
				"You live with a curse that causes you to become savage—even feral—to the point where your body physically changes. At the start of the Dusk Phase, roll with Composure or Sensitivity, your choice. <strong>On a 10+,</strong> your body is stronger and faster, and you manage to keep the quickening in check. You roll with advantage when taking actions that use Vitality until the next Dawn Phase. <strong>On a 7-9,</strong> you manage to keep the quickening in check, but just barely; take the following Condition: Drained. If you’re already Drained, put on a Mask. ",

				"<strong>On a miss,</strong> you’re going to lose control: ",
				"<li>Retire this character and tell the Keeper to put The Cursed in play OR </li>",
				"<li>Reveal your curse to another Hunter and ask for their help controlling you tonight. If they agree, neither of you can take any action that would trigger a move during the upcoming Night Phase, though you should narrate scenes showing how the cursed character is being controlled throughout the night. During the Dawn Phase, you each mark 1 XP. Additionally, they get to define something interesting about your transformation; that information is a Clue that can be used for The Cursed. This option can only be chosen once.</li>",

				"<strong>On a 12+,</strong> you can control your transformation. If you wish, change into the feral beast. What do you turn into? While in this state, your Vitality and Sensitivity are each increased by 1 (max 4) and your Reason is reduced by 2. Additionally, your heightened sense of hearing and smell will help you uncover an additional Clue no other Hunter would be able to detect. During the Dawn Phase, tell the Keeper what the Clue is; it cannot conclusively answer a Question by itself. Finally, the other Hunters get to define something interesting about your transformation; that information is a Clue that can be used for The Cursed. You return to normal at the start of the Dawn Phase.",
			],
		},
		{
			title: "Awakened Soul",
			text: [
				"You are sensitive to the desires and behaviors of animals. When you <strong>encounter an animal,</strong> you may ask the Keeper, “What does this animal want me to do?” The Keeper will answer truthfully and completely. When you <strong>act on the answer or pursue a course of action in which an intuitive understanding of an animal’s behavior</strong>  would be helpful, any associated rolls are taken with advantage. ",
			],
		},
		{
			title: "Fastest Gun in the West",
			text: [
				"When you take this move, add the 1851 Colt Navy Revolver to your Personal Quarters. This item is never marked when using it to take advantage on a die roll. After a roll, you can choose to mark it in order to re-roll one die of your choice.",
			],
		},
		{
			title: "As Cruel As the Harlot's Curse",
			text: [
				"When you indulge your Vice—with no other Hunters present—in the dark and seedy underbelly of London in order to deaden your senses, roll with Vitality. <strong>On a hit,</strong> clear a Condition and choose one from the list below. <strong>On a 10+,</strong> choose two.",
				"<li>You don’t draw any unwanted attention.</li>",
				"<li>You befriend a Side Character.</li>",
				"<li>You gain some mastery over your curse; on your next Quickening roll, increase the success tier by one step.</li>",
				"<li>You stumble on a Clue. Tell the Keeper what it is. The Clue cannot conclusively answer a Question by itself.</li>",
				"<strong>On a 12+</strong>, you take a memento; ask another Hunter what it is and then put it in your Personal Quarters.",
			],
		},
	],
	advancements: [
		"Increase an ability modifier by 1 (max 3)",
		"Increase an ability modifier by 1 (max 3)",
		"Increase an ability modifier by 1 (max 3)",
		"Choose an additional move from your playbook.",
		"Choose an additional move from your playbook.",
		"Write a custom move for your character.",
		"Unmark everything in your Personal Quarters.",
	],
};
