import type { PlaybookBase } from "../types"

export const motherPlaybook: PlaybookBase = {
  title: "The Mother",
  intro: [
    "Few understand the mysteries of human anatomy like you do. You are one of the most brilliant medical minds in London and could take your place as a lecturer at any number of esteemed academies. But you have different ideas, different plans; you are no longer interested in merely preserving life, but creating it! And so you’ll do what you must to survive—tending to the prostitutes dying of consumption, assisting Scotland Yard with grisly, forensic inquiry, and creeping about in the dark with these new people, these Hunters with whom you share a home—but always you are focused on the new life growing in your secret womb, your child, the one you hope will capture even the faintest reflection of the person you loved and lost. ",
  ],
  names: {
    firstName: [
      "John",
      "Thomas",
      "William",
      "Richard",
      "Robert",
      "Samuel",
      "Michael",
      "Geoffrey",
      "Jaques",
      "Vishwanath",
      "Malick",
      "Victor",
      "Mary",
      "Susanna",
      "Elinor",
      "Alice",
      "Dorothy",
      "Grace",
      "Hiba",
      "Shaoming",
      "Ravathi",
      "Paloma",
    ],
    surname: [
      "Stockmore",
      "Branford",
      "Beckland",
      "Fenworth",
      "Swindrake",
      "Somerrich",
      "Norhurst",
      "Clayridge",
      "Wickton",
      "Safby",
      "al-Kabir",
      "Waldschmidt",
      "Ghoshal",
      "Carrión",
      "Blakeman",
      "Johansen",
      "Weiss",
    ],
  },
  look: [
    "bowler hat",
    "second-hand silk hat",
    "close-cropped hair",
    "sunken eyes",
    "piercing eyes",
    "rimless eyeglasses with tortoise shell detail",
    "spectacles with yellow-smoked lenses",
    "hollowed-out cheeks",
    "pale skin",
    "five o’clock shadow",
    "unkempt beard",
    "tartan dress",
    "Indian “cone” pattern dress",
    "white shirt and fawn trousers",
    "vermillion waistcoat",
    "Navy blue frock coat",
    "buckskin trousers",
    "clean and unadorned hands",
    "calfskin gloves",
    "leather Wellingtons",
    "worn work boots",
  ],
  vices: ["cigarettes", "coffee", "Turkish baths", "cleansing tonics", "voyeurism"],
  questions: [
    "Did you dismiss the possibility of a supernatural explanation despite everything you’ve experienced?",
    "Did you secretly engage in romantic or emotional behavior at odds with your aloof, logical exterior?",
    "Did you put your hands in a pile of guts and love every moment of it?",
    "Did you show physical affection toward the Child while someone else was looking?",
    "Did you have a conversation with the Child while no one was looking?",
  ],
  abilities: {
    vitality: 0,
    composure: 1,
    reason: 1,
    presence: 0,
    sensitivity: 0,
  },
  masksOfPast: [
    "You lost someone very important to you. Who were they? Name them.",
    "Narrate a flashback to the first time you experienced love for the person you lost.",
    "Narrate a flashback to the happiest day you shared with the person you lost.",
    "Narrate a flashback to the time you had a terrible fight with the person you lost.",
    "Narrate a flashback to the time when you first realized you and the person you lost weren’t going to be together forever.",
    "Narrate a flashback to the time when the person you lost was slipping away from you.",
    "Narrate a flashback to the time when you finally said goodbye to the person you lost.",
  ],
  masksOfFuture: [    
    "<strong>The Guilded Door</strong>: Take the following Condition: Most-Beloved. Tell the other Hunters they can no longer choose The Gilded Door on their own playbook (this does not count as being marked for them). You can never clear Most-Beloved.",
    "<strong>The Moss-Covered Gate</strong>: You must attempt to bring the Child to life. ",
    "<strong>The Darkened Threshold</strong>: Narrate a scene in which you destroy a professional rival.",
    "<strong>The Cosmic Passage</strong>: Increase your Sensitivity by 1 (max 3).",
    "<strong>The Blood-Soaked Portal</strong>: Narrate a scene in which you are physically destroyed. This character is now retired. ",
  ],
  startingMoves: ["The Child"],
  moves: [
    {
      title: "The Child",
      text: [
        "You have a secret laboratory in Hargrave House where you are building a person from body parts you acquire in the city. When the time is right, you will use principles of chemistry and alchemy to give your creation life. When you acquire a body part for the Child, narrate a brief, pleasant memory of the person you lost that is triggered by holding the part in your hands.",
        "When you acquire all the necessary parts or are instructed to do so by the Mask of the Future, you attempt to bring the Child to life and roll with Reason. If you have acquired all the parts, you can disregard the result of the roll and pick whichever outcome you like. ",
        "<li><strong>On a 10+</strong>, the Child is alive, and they love you very much. You may add the following to your Dawn questions (it is always selected): “Did you teach the Child a lesson about what it means to be human?”</li>",
        "<li><strong>On a 7-9,</strong> the Child is alive, but it is a disappointment or a horror. Retire this character to obscurity; The Orphan (Hunter) is now available.</li>",
        "<li><strong>On a miss,</strong> the Child is alive and consumed by anger and fear. Tell the Keeper to put The Orphan (Threat) in play.</li>",
      ],
    },
    {
      title: "Night Work",
      text: [
        "During a Hargrave House Night Phase, you spend the evening doing house calls, helping Scotland Yard examine corpses dragged from the river, and, of course, working on the Child. Choose three from the list below during the Dawn Phase that follows:",
        "<li>You find a Clue; the Keeper will describe it.</li>",
        "<li>You find a Clue that can be used for a future Threat; tell the Keeper what the Clue is.</li>",
        "<li>You acquire a body part for the Child (can be chosen more than once).</li>",
        "<li>You find a keepsake; ask another Hunter what it is and then add it to your Personal Quarters.</li>",
      ],
    },
    {
      title: "Field Medicine",
      text: [
        "When you <strong>treat someone’s physical injuries,</strong> roll with Composure. <strong>On a hit,</strong> a fellow Hunter suffers no die roll penalties from a physical Condition (however, the Condition is not cleared). A Side Character is stabilized or their life is saved. <strong>On a 10+</strong>, if appropriate (or with the consent of their player in the case of treating a Hunter), you also manage to get a body part for the Child. ",
      ],
    },
    {
      title: "Beneath the Skin",
      text: [
        "When you examine a corpse, you may ask the Keeper two of the following:",
        "<li>How did this person die? The Keeper will answer with a Clue.</li>",
        "<li>What would an untrained eye overlook here? The Keeper will answer with a Clue.</li>",
        "<li>Can I take a body part for the Child without anyone noticing? If the Keeper says yes, acquire a body part for the Child. If the Keeper says no, you can still attempt to take the body part, possibly triggering other moves.</li>",
      ],
    },
    {
      title: "Infirmary",
      text: [
        "Tell the Keeper to put the Infirmary in play. Add Medical Texts to your Personal Quarters; this item is never marked.",
      ],
    },
    {
      title: "The Resurrectionists",
      text: [
        "A gang of graverobbers led by a man called Harley White (dingy workman’s clothes, cracked teeth, smells of gravedirt) is loyal to you. Each Dusk Phase, pick two:",
        "<li>The graverobbers will dig up corpses that night; during the Dawn Phase, acquire a body part for the Child.</li>",
        "<li>The graverobbers will search for other valuables that night; during the Dawn Phase, ask another Hunter what they found and add it to your Personal Quarters.</li> ",
        "<li>A graverobber, either Harley or another (name them), will accompany you during the upcoming Night Phase. Take the following Condition: Ghoulish. Any rolls associated with actions the graverobber is helping you with are taken at advantage. </li>",
        "<li>You’ll face no blowback or complications from any criminal activities the graverobbers get up to that night. </li>",
      ],
    },
  ],
  advancements: [
    "Increase an ability modifier by 1 (max 3)",
    "Increase an ability modifier by 1 (max 3)",
    "Increase an ability modifier by 1 (max 3)",
    "Choose an additional move from your playbook.",
    "Choose an additional move from your playbook.",
    "Write a custom move for your character.",
    "Unmark everything in your Personal Quarters.",
  ],
}
