import type { PlaybookBase } from "../types"

export const orphanPlaybook: PlaybookBase = {
  title: "The Orphan",
  intro: [
    "Note: This playbook can only be selected as a result of <strong>The Child</strong> move on The Mother playbook.",
    "You were not. And then, quite suddenly, you were. The only thing you remember of your creator is their face, twisted in anguish and disappointment. They abandoned their work with Hargrave House, and left you here, orphaned… but not alone. The others—the Hunters—they found you. They helped you remember how to speak, and were kind to you in their way. They let you stay in the laboratory, and made it comfortable for you; they gave you things from the outside world to help you better understand it. Like them, you are a creature of the shadows, and you always will be. But unlike them, you understand there can be no shadows without light. ",
  ],
  names: {
    name: [
      "Adam",
      "Josef",
      "Emmet",
      "Rhodes",
      "Clay",
      "Boris",
      "Manu",
      "Adapa",
      "Epimetheus",
      "Ask",
      "Eve",
      "Eliza",
      "Embla",
      "Pandora",
      "Lilith",
      "Mashyana",
      "Elsa",
      "Mary",
      "Susana",
      "Galatea",
    ],
  },
  look: [
    "moth-eaten top hat",
    "bilgewater black hair",
    "prominent facial scar",
    "empty eye socket",
    "blackened teeth",
    "exposed jawbone",
    "misshapen head",
    "distended tattoos",
    "prominent stitches holding you together",
    "black duster",
    "twisted spine",
    "taxidermied (pick one: owl/crow/weasel/something else)",
    "oversized and undersized limbs",
    "mutton fists",
    "weeping pustules",
    "trousers covered in patches",
    "black dress with petticoat",
    "striped stockings",
    "shackles",
    "muddy boots",
  ],
  vices: ["poetry", "tea & biscuits", "helping animals", "high places", "breaking things"],
  questions: [
    "Did you watch someone from the shadows, your heart filled with longing? ",
    "Did you use brute strength to get your way? ",
    "Did you deliver an embittered monologue about being abandoned by your creator? ",
    "Were you extra gentle with someone or something because you know how strong you are? ",
    "Did you openly walk among people during the day? ",
  ],
  abilities: {
    vitality: 2,
    composure: 0,
    reason: 0,
    presence: 0,
    sensitivity: 0,
  },
  masksPastDescription:
    "You don’t have a true past. Instead, the spirits attached to the body parts you are constructed from stir up memories that are not yours. You can live with these memories or learn to quiet them.",
  masksOfPast: [
    "Narrate a flashback to someone’s childhood in which they are showered with love. Then, if you wish, describe how you quiet this part of you.",
    "Narrate a flashback to someone’s wedding day. Then, if you wish, describe how you quiet this part of you.",
    "Narrate a flashback to when someone’s first child was born. Then, if you wish, describe how you quiet this part of you.",
    "Narrate a flashback to the time someone lost their mother. Then, if you wish, describe how you quiet this part of you.",
    "Narrate a flashback to the first time someone journeyed across the sea. Then, if you wish, describe how you quiet this part of you.",
    "Narrate a flashback to the time someone lost all hope. Then, if you wish, describe how you quiet this part of you.",
    "Narrate a flashback to the moment someone was brutally murdered. Then, if you wish, describe how you quiet this part of you.",
  ],
  masksOfFuture: [
    "<strong>The Darkened Threshold</strong>: Narrate a scene in which you engage in self-destructive behavior because of the way society treats you.",
    "<strong>The Cosmic Passage</strong>: Increase your Sensitivity by 1 (max 3).",
    "<strong>The Blood-Soaked Portal</strong>: Narrate a scene in which you are physically destroyed. This character is now retired. ",
  ],
  startingMoves: ["The Family"],
  moves: [
    {
      title: "The Family",
      text: [
        "You help Hargrave House in order to earn your keep, but the people who live there can never be your family since they are even more broken than you are. There is another group of people in London you watch from afar in the hopes they will someday notice and accept you.",
        "The group you hope to join is suffering from a problem. You will secretly help the group solve this problem and then, when the time is right, present yourself to them. From now on, when you would collect a Reward from resolving a Threat, instead mark a box below and describe how something from the recently resolved Threat can be used to help the group with their problem.",
        "When all three boxes are marked, roll with Presence; this roll is always made at disadvantage. <strong>On a 10+,</strong> they are thankful for your help and welcome you as one of their own. Narrate a short epilogue showing your life with your new family. This character is now retired. <strong>On a 7-9,</strong> they shun you and call you unkind names. Unmark a box from this move. <strong>On a miss,</strong> they are horrified, and turn on you. Mark <strong>The Blood-Soaked Portal.</strong> ",
      ],
      checkboxes: 3,
    },
    {
      title: "Caliban's Fury",
      text: [
        "You are as strong as ten men, and even stronger when you’re angry. Take advantage on any die rolls associated with actions involving raw strength. Add 1 to the roll if you have any negative emotional Conditions (<strong>A Disappointment and a Horror</strong> does not count). ",
      ],
    },
    {
      title: "Day Work",
      text: [
        "When not engaged in the hunt with the residents of Hargrave House, you spend your days performing small acts of kindness from the shadows. During the Dawn Phase, you can say you’re going to do Day Work, in which case you take no action during the Day Phase. Instead, as a player, describe something pleasant or hopeful in the other Hunters’ scenes. Then choose three from the list below during the Dusk Phase that follows:",
        "<li>You find a Clue; the Keeper will describe it. </li>",
        "<li>You find a Clue that can be used for a future Threat; tell the Keeper what it is. </li>",
        "<li>You make a friend; name them and describe them. They are a Side Character. </li>",
        "<li>You find a treasure; ask another Hunter what it is. If you keep it, add it to your Personal Quarters. If you give it to another Hunter, they add it to their Personal Quarters and you mark XP. </li>",
      ],
    },
    {
      title: "The Titan's Ember",
      text: [
        "You can produce fire equal to that of a torch from your hands. You can also control existing fires within eyesight by doubling their intensity or reducing their size by half. You can snuff a candle or lantern from twenty paces.",
      ],
    },
    {
      title: "Quicksilver Voice",
      text: [
        "You are a gifted conversationalist and deeply sympathetic to those who hear you speak—but only if they can’t see you. Take advantage on any die rolls associated with actions involving speech or persuasion so long as you are doing so from the shadows or are otherwise physically obscured. ",
      ],
    },
    {
      title: "The Burning Aperture",
      text: [
        "You are a physical manifestation of creative energy, a literal portal between idea and execution. So long as you are present in the scene, when a fellow Hunter would mark the Mask of the Future, they can mark this move instead and describe how your energy pushes them to success. When all three boxes are marked, mark XP. ",
      ],
      checkboxes: 3,
    },
  ],
  advancements: [
    "Increase an ability modifier by 1 (max 3)",
    "Increase an ability modifier by 1 (max 3)",
    "Increase an ability modifier by 1 (max 3)",
    "Choose an additional move from your playbook.",
    "Choose an additional move from your playbook.",
    "Write a custom move for your character.",
    "Unmark everything in your Personal Quarters.",
  ],
}
