import type { PlaybookBase } from "../types"

export const undeniablePlaybook: PlaybookBase = {
  title: "The Undeniable",
  intro: [
    "You have always been the most beautiful person in the room. Your looks have opened doors for you for as long as you can remember—all the money and material things anyone could want, laid at your feet. Artists have found inspiration in the brightness of your eyes, the delicate curve of your cheekbones, the plump softness of your lips. One such artistic work, a masterwork, rises above them all, for it captures the essence of you–it is, quite simply, more you than you. Lately, people sacrifice everything to be near you, to please you, and, if they’re lucky, to touch you. But what to do when you get bored with being one of the gods?",
  ],
  names: {
    firstName: [
      "Kemuel",
      "Francis",
      "Ishaq",
      "Baston",
      "Lucas",
      "André",
      "Parsifal",
      "Benedek",
      "Riccalbano",
      "Dauntay",
      "Bennu",
      "Shai",
      "Cara",
      "Kathegras",
      "Alina",
      "Eva",
      "Cecilie",
      "Adelheid",
      "Dimitra",
      "Neethi",
    ],
    surname: [
      "Robel",
      "Lepince",
      "al-Shirazi",
      "Bonhomme",
      "Richter",
      "Andrássy",
      "Giacone",
      "Shibukawa",
      "Saihan",
      "Leuva",
      "Latimer",
      "Tagaris",
      "Kemp",
      "Harington",
      "Gray",
      "Quinn",
      "Falcone",
    ],
  },
  look: [
    "meticulous coiffure",
    "golden olive branch crown",
    "flawless skin",
    "pearl-studded head cage",
    "blue-gray eyes",
    "long dressing gown with Hellenic patterns",
    "topaz kimono",
    "dress with gold rope embroidery",
    "peacock blue sari",
    "ostrich feather cape",
    "plum velvet smoking jacket",
    "gold and maroon sherwani",
    "black mesh shirt",
    "Turkish style pants",
    "perfectly-tailored corduroy trousers",
    "tight-fitting jodhpurs",
    "sheer gloves",
    "understated jewelry",
    "ruby-encrusted riding crop",
    "fine silk hosiery",
    "velvet loafers",
    "ermine-lined slippers",
    "tall boots",
  ],
  vices: ["cocaine", "floggings", "extravagant spending", "memento mori photographs", "comforting the dying"],
  questions: [
    "Did you express a clear preference for the beautiful over the mundane?",
    "Did you secretly show a vulnerable side to someone?",
    "Did you create an ornate, over-the-top erotic experience for someone else’s pleasure?",
    "Did you appear in London society wearing risque or avant-garde fashion?",
    "Did you let someone touch you and then make them pay a price for doing so?",
  ],
  abilities: {
    vitality: 1,
    composure: 0,
    reason: -1,
    presence: 2,
    sensitivity: 0,
  },
  masksOfPast: [
    "Narrate a flashback to your childhood that shows how, even then, people were willing to suffer in order to make you happy.",
    "Narrate a flashback to your young adulthood that shows the first time you met the artist who fell in love with you.",
    "Narrate a flashback that shows when you cruelly discarded the artist.",
    "Narrate a flashback to a scene when the artist destroyed themselves because of your rejection. How did the masterwork change in order to reflect your cold indifference?",
    "Narrate a flashback to when you first met the person you fell madly in love with.",
    "Narrate a flashback that shows why you started to become jealous of the person you fell madly in love with. How did the masterwork change to reflect this simmering resentment?",
    "Narrate a flashback to when you finally destroyed the person you fell madly in love with. How did the masterwork change to reflect your wrath?",
  ],
  masksOfFuture: {
    "The Guilded Door":
      "Take the following Condition: Most-Beloved. Tell the other Hunters they can no longer choose The Gilded Door on their own playbook (this does not count as being marked for them). You can never clear Most-Beloved.",
    "The Moss-Covered Gate": "Narrate a scene in which you express private regret for the harm you have caused. ",
    "The Darkened Threshold":
      "Whenever you gaze upon the masterwork in an attempt to uncover something hidden in the world, roll with Sensitivity. <li><strong>On a 10+,</strong> the masterwork reveals a Clue or a Mastermind Clue, your choice.</li> <li><strong>On a 7-9,</strong> as above, but you also scar your Reflection.</li> ",
    "The Cosmic Passage": "Narrate a scene during which people treat you like you’re nothing special. ",
    "The Blood-Soaked Portal": "Narrate a scene in which you are physically destroyed. This character is now retired. ",
  },
  startingMoves: ["The Reflection"],
  moves: [
    {
      title: "The Reflection",
      text: [
        "Somewhere in London, hidden from the world, is a masterwork created in your image or otherwise inspired by your beauty. It is guarded by a cult dedicated to your worship.",
        "The masterwork will gradually degrade so you can remain young and beautiful, and will bear the scars that your evil acts would otherwise leave on your soul. Whenever you <strong>scar your Reflection, either as the result of a move or because the Keeper said to,</strong> mark a box below and describe how the masterwork has changed for the worse.",
        "When <strong>all the boxes are marked,</strong> you must frame an intimate scene with a fellow Hunter where you reveal the masterwork to them and explain some of the terrible things you have done that are reflected in it. Then, if you wish, throw yourself at their feet and beg them for redemption. They can grant it by taking you into a passionate embrace, then and there. If they do so, describe how you embrace a life of humility and grace, then retire this character.",

        "If the other Hunter does not grant redemption, or if you choose not to ask for it, ask the Keeper to narrate a scene in which we see you become a servant of the Mastermind, then retire this character. ",
      ],
      checkboxes: 12,
    },
    {
      title: "Unquenchable Thirst",
      text: [
        "Your physical beauty is not only unparalleled, it is aggressively eternal. During the Dusk Phase, clear all Conditions related to your physical appearance. When you do so, scar your Reflection. When you perform an action that leverages your physical appearance, associated rolls are taken with advantage.",
      ],
    },
    {
      title: "Giveth",
      text: [
        "At any time, you can declare that a Side Character is secretly one of your worshippers. Describe how the Side Character subtly or not-so-subtly debases themselves before you in the scene, then scar your Reflection. Whenever you <strong>make a gift of something from your Personal Quarters to a worshipper</strong>, they will do exactly as you say, no questions asked, up to and including destroying themselves. If you demand information from them, it may come in the form of a Clue, at the Keeper’s discretion.",

        "If another Hunter debases themselves at your feet, they may take the following Condition: Worshipper. If they do so, they mark XP and you scar your Reflection. So long as they have the Condition, the following is added to their Dawn Question list (it is always marked): “Did you continue to perfect your worship of the Undeniable?” You get to answer for them. If you say “Yes,” you mark XP instead of them, then give them something from your Personal Quarters, which goes on their sheet unmarked.",
      ],
    },
    {
      title: "Taketh Away",
      text: [
        "When you destroy a Side Character—physically, spiritually, or socially—describe how it makes you feel, scar your Reflection, and roll with Vitality.<strong>On a 10+,</strong> choose two. <strong>On a 7-9,</strong> choose one. If the Side Character is a worshipper, there is no need to roll; choose three.",
        "<li>Clear any Conditions you wish, including Most-Beloved.</li>",
        "<li>Your next roll is taken with advantage. </li>",
        "<li>You may take something from your victim and add it to your Personal Quarters.</li>",
        "<li>There are no long-term consequences for your actions. </li>",
      ],
    },
    {
      title: "The Collection",
      text: [
        "You have access to a collection of rare, one-of-a-kind objects. When you take this move, circle an item and add it to your Personal Quarters. If you ever use one of these items during a sensual encounter with another Hunter, erase it from your Personal Quarters and add it to theirs, unmarked. You can circle another item and add it to your Personal Quarters at any time by scarring your Reflection.",

        "<li>An apple from the Garden, Lot’s wife, Judith’s knife, Cleopatra’s veil, Patroclus’s spear, Caligula’s saddle, Julius Caesar’s blood-stained toga, Joan of Arc’s ashes, the Holy Grail, the Virgin Queen’s neck ruff, Catherine the Great’s hand fan, Marie Antoinette’s stockings, Casanova’s perfume, Barbara Villier’s corset, Madame de Pompadour’s wig, Louis XIV’s shoes, John Wilkes Booth’s death shroud</li>",
      ],
    },
    {
      title: "The Menagerie",
      text: [
        "You have a private room in Hargrave House, down a little-used corridor, accessible only with a jeweled, brass key tied to a velvet cord. When you take this move, add the Jeweled Key to your Personal Quarters and tell the Keeper to put the Menagerie in play.",
      ],
    },
  ],
  advancements: [
    "Increase an ability modifier by 1 (max 3)",
    "Increase an ability modifier by 1 (max 3)",
    "Increase an ability modifier by 1 (max 3)",
    "Choose an additional move from your playbook.",
    "Choose an additional move from your playbook.",
    "Write a custom move for your character.",
    "Unmark all the boxes on The Reflection (the masterwork itself is unchanged)..",
  ],
}
