import type { PlaybookBase } from "../types";

export const vesselPlaybook: PlaybookBase = {
	title: "The Vessel",
	intro: [
		"For as long as you can remember, dark entities have been near. They lurk just inside your peripheral vision, just at the mirror’s edge. When you close your eyes, you can actually feel them: their cold breath, their oily touch… an occasional feverish embrace. They want to be inside you; they want to rub against your guts and deposit their power. Others are drawn to you as well: those who would use you to master these dark things in order to serve their own agenda. Some of these interlopers, these usurpers, can be of use, such as the Hunters with whom you share a home. Others, like the coven, are best avoided. In either case, you are no one’s object, tool, or weapon; you are no mere bystander. Your fate is yours to shape.",
	],
	names: {
		firstName: [
			"Helena",
			"Ardent",
			"Hence",
			"Colizabel",
			"Robeth",
			"Isabert",
			"Lepinna",
			"Regess",
			"Priyanka",
			"Roberta",
			"Caul",
			"Bragen",
			"Clance",
			"Mortio",
			"Orlence",
			"Micham",
			"Lancell",
			"Dai",
			"Liam",
			"Dederich",
		],
		surname: [
			"Talifford",
			"Thop",
			"Arcpenney",
			"Aufford",
			"Henbury",
			"Caesbury",
			"Sand",
			"al-Najjar",
			"Dolorfino",
			"Sabine",
			"Unruh",
			"Lekas",
			"Bellacqua",
			"Inoue",
			"Rao",
			"Davies",
			"Jaggard",
		],
	},
	look: [
		"silk hat with purple ribbons",
		"a dark green veil with tiny onyx woven in",
		"asymmetrical haircut",
		"silver hairpins",
		"red-stained lips",
		"mismatched eyes",
		"jeweled eye patch",
		"black velvet coat with blood-red trim",
		"choker with an amber jewel",
		"upside down Christian cross necklace",
		"lace shirt with stiffened collar",
		"corset-trained",
		"tailored men’s suit in burgundy and black",
		"deep purple dress with petticoat",
		"black lace gloves",
		"raven feather cuffs",
		"onyx and amethyst jewelry",
		"bracelet with zodiac charms",
		"parasol with delicate spider web motif",
		"tall-heeled boots with vermillion laces",
		"short boots with plum velvet trim",
	],
	vices: [
		"absinthe",
		"morphine",
		"sex with dark entities",
		"Sunday morning mass",
		"examining your own blood",
	],
	questions: [
		"Did you have a face-to-face encounter with a dark entity?",
		"Did you counsel someone using your supernatural affinities as the basis for that advice?",
		"Did you perform a ritual?",
		"Did you make love to a human in order to forget the darkness?",
		"Did you make love to a dark entity because you wanted to?",
	],
	abilities: {
		vitality: -1,
		composure: 0,
		reason: 1,
		presence: 1,
		sensitivity: 1,
	},
	masksOfPast: [
		"Narrate a flashback to the time when you were in your mother’s womb that shows, even then, dark entities were interested in you. ",
		"Narrate a flashback to your childhood that shows the first time you encountered a dark entity. ",
		"Narrate a flashback to your young adulthood that shows your first sexual encounter with a dark entity. ",
		"Narrate a flashback to your young adulthood that shows a time when you used your supernatural affinities for selfish purposes. ",
		"Narrate a flashback to your young adulthood that shows when you first met the leader of the coven. Name them. ",
		"Narrate a flashback to your young adulthood that shows part of your initiation into the coven. Name the coven. ",
		"Narrate a flashback to an event that influenced you to leave the coven for good. ",
	],
	masksOfFuture: {
		"The Guilded Door":
			"Take the following Condition: Most-Beloved. Tell the other Hunters they can no longer choose The Gilded Door on their own playbook (this does not count as being marked for them). You can never clear Most-Beloved.",
		"The Moss-Covered Gate":
			"Tell the Keeper to put The Coven in play. The Keeper should immediately frame a scene showing that the Coven has arrived in London. ",
		"The Darkened Threshold":
			"Narrate a scene in which, possessed by a dark entity, you harm an innocent.",
		"The Cosmic Passage":
			"Increase your Sensitivity by 1 (max 3) and reduce your Reason by 2.",
		"The Blood-Soaked Portal":
			"Narrate a scene in which you are physically destroyed. This character is now retired. ",
	},
	startingMoves: ["Rites of Salt & Smoke"],
	moves: [
		{
			title: "Rites of Salt & Smoke",
			text: [
				"You are skilled at contacting dark entities in order to perform magical rituals. When you give offerings to the dark entities that are always lingering in your peripheral vision, roll with Sensitivity. <strong>On a 10+,</strong> the magic works without further cost: choose your effect. <strong>On a 7-9,</strong> the magic works imperfectly: choose your effect and a complication.",

				"<strong>Effects</strong>",
				"<li>Do one thing that is beyond human limitations.</li>",
				"<li>Bar a place or portal to a specific person or creature.</li>",
				"<li>Trap a specific person or creature.</li>",
				"<li>Banish a spirit or curse from the person, object, or place it inhabits.</li>",
				"<li>Communicate with someone or something that you do not share a language with.</li>",
				"<li>Observe another place or time.</li>",

				"<strong>Complications</strong>",
				"<li>The effect is less than you wanted.</li>",
				"<li>The effect is short-lived.</li>",
				"<li>You take a Condition; the Keeper will tell you what.</li>",
				"<li>The magic draws immediate, unwanted attention.</li>",
				"<li>The magic has a problematic side effect.</li>",
				"<strong>On a 12+,</strong> you can unmark The Cosmic Passage if it is marked. If you do so, increase your Reason by 2 but leave your Sensitivity the same. Ignore this result if your Sensitivity is 3.",
			],
			extraLines: 1,
		},
		{
			title: "A Thinning of the Veil",
			text: [
				"When you take this move, choose your divination tools and add them to your Personal Quarters:",
				"<li>Tarot cards</li>",
				"<li>Star charts</li>",
				"<li>Rune stones</li>",
				"<li>___________ (write your own)</li>",
				"When you consult your divination tools to glimpse the future, roll with Sensitivity. <strong>On a hit,</strong> you may ask “What is about to happen?” The Keeper will answer truthfully but not necessarily completely. <strong>On a 10+,</strong> you may also ask “Why is this about to happen?” <strong>On a 12+,</strong> you also find a Clue; the Keeper will describe it. ",
				"<strong>On a miss,</strong> you instead glimpse a terrible fate awaiting one of your fellow Hunters. Hold 1. Just before they roll for a move, you may spend the hold to say, “The [cards/stars/runes/x] have shown me this is how you’re going to die.” They then choose to back down or go through with it. If they go through with it, they mark a box on their XP track, but the miss result on their move is replaced with, “Your character is immediately retired from the game. The Vessel will describe it.”",
			],
		},
		{
			title: "A Beacon in the Dark",
			text: [
				"When you walk the streets of London at night, your consciousness spreading across the city like a vast spider web, roll with Sensitivity. <strong>On a hit,</strong> you are immediately confronted by a Threat or a personified Danger related to the Threat. You may ask them two questions from the list below. They will not answer directly, but rather in the form of a Clue. <strong>On a 10+,</strong> the Threat or Danger departs as soon as the questions are answered.",
				"<li>Where is your lair?</li>",
				"<li>How can I get you to ________?</li>",
				"<li>What do you intend to do?</li>",
				"<li>What do you want from ________?</li>",
				"<li>What frightens you?</li>",
			],
		},
		{
			title: "Witch's Cupboard",
			text: [
				"You have a cupboard in Hargrave House containing supplies needed for rituals and remedies. When you take this move, choose three (or write your own) and add them to your Personal Quarters. The cupboard can then be used five additional times, by you or another Hunter. When a Hunter searches the cupboard for something to help them with a ritual, they can choose one (or make up their own) and add it to their Personal Quarters.",

				"<li>Candles, altar cloth, frankincense, pendulum, herbs, athamé, essential oils, feathers, salt, florid water, holy water, unholy water, quartz crystals, crystal ball, gravedirt, feathers, charcoal sticks, lavender ash, broom, statues of saints, statue of The Green Man, rosary beads, Christian symbols, chime</li>",
			],
			checkboxes: 5,
		},
		{
			title: "Ritual Chamber",
			text: [
				"You have prepared one of the rooms in Hargrave House to be a place for performing powerful magic.  Increase your Reason by 1 (max 3) and tell the Keeper to put the Ritual Chamber in play.",
			],
		},
		{
			title: "Familiar",
			text: [
				"You have a small animal companion through which you can work some of your magic. When you take this move, choose your companion, name it, and add it to your Personal Quarters; it can never be marked so long as the die roll you are taking advantage on is associated with magic related to the familiar’s listed affinity.",
				"<li>Toad (harming others)</li>",
				"<li>Crow (seeing distant places)</li>",
				"<li>Cat (drawing things to you)</li>",
				"<li>Snake (uncovering forbidden knowledge)</li>",
				"<li>Owl (rituals worked at night)</li>",
			],
		},
	],
	advancements: [
		"Increase an ability modifier by 1 (max 3)",
		"Increase an ability modifier by 1 (max 3)",
		"Increase an ability modifier by 1 (max 3)",
		"Choose an additional move from your playbook.",
		"Choose an additional move from your playbook.",
		"Write a custom move for your character.",
		"Unmark everything in your Personal Quarters.",
	],
};
